services:
    eliza:
        container_name: grantolf
        #command: ["pnpm", "start", "--character=./characters/grantolf.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        restart: always
        ports:
            - "3000:3000"
            - "5173:5173"
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - ./eliza:/app/packages/client-twitter/src/tweetcache
            - ./eliza:/app/db.sqlite
        networks:
            - grantolf
        env_file:
            - .env
            # Refer to: https://github.com/elizaOS/eliza/blob/develop/.env.example for all available environment variables

networks:
    grantolf:
        driver: bridge