name: update-agent

on:
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Update Agent
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 200m
          script: |

            #alias pm2=/home/gmadmin/.nvm/versions/node/v23.9.0/bin/pm2
            #alias pnpm=/home/gmadmin/.local/share/pnpm/pnpm
            # We'll track if we successfully updated
            UPDATE_SUCCESS=true
            
            # Change directory
            cd $HOME/grantolf-eliza
            chmod +x ./client/node_modules/@esbuild/linux-x64/bin/esbuild
            # Only proceed if previous step succeeded
            git reset --hard origin/main
            
            # Only proceed if previous steps succeeded
            git pull origin main
            
            /home/gmadmin/.nvm/versions/node/v23.9.0/bin/pm2 stop grantolf
            /home/gmadmin/.nvm/versions/node/v23.9.0/bin/pm2 delete grantolf

            # Try to build the new image without affecting the running container
            /home/gmadmin/.local/share/pnpm/pnpm i && /home/gmadmin/.local/share/pnpm/pnpm build
            
            # Only remove and restart grantolf if all previous steps (including build) succeeded
            pm2 start /home/gmadmin/.local/share/pnpm/pnpm --name "grantolf" -- start --character=./characters/grantolf.character.json