name: update-agent

on:
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Update Agent
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 200m
          script: |
            echo "Check node version"
            node -v
            echo "Check pnpm version"
            pnpm -v
            echo "Check pm2 version"
            pm2 -v
            # Change directory
            cd $HOME/grantolf-eliza
            chmod +x ./client/node_modules/@esbuild/linux-x64/bin/esbuild
            # Only proceed if previous step succeeded
            git reset --hard origin/main
            
            # Only proceed if previous steps succeeded
            git pull origin main
            
            pm2 stop grantolf
            pm2 delete grantolf

            # Try to build the new image without affecting the running container
            pnpm install --no-frozen-lockfile && pnpm build
            
            # Only remove and restart grantolf if all previous steps (including build) succeeded
            pm2 start pnpm --name "grantolf" -- start --character=./characters/grantolf.character.json